# automatically generated by the FlatBuffers compiler, do not modify

# namespace: nbody

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FrameSample(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FrameSample()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFrameSample(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def FrameSampleBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x42\x46\x52", size_prefixed=size_prefixed)

    # FrameSample
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FrameSample
    def Frame(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # FrameSample
    def BodyCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # FrameSample
    def Bodies(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # FrameSample
    def BodiesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # FrameSample
    def BodiesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FrameSample
    def BodiesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def FrameSampleStart(builder):
    builder.StartObject(3)

def Start(builder):
    FrameSampleStart(builder)

def FrameSampleAddFrame(builder, frame):
    builder.PrependUint32Slot(0, frame, 0)

def AddFrame(builder, frame):
    FrameSampleAddFrame(builder, frame)

def FrameSampleAddBodyCount(builder, bodyCount):
    builder.PrependUint32Slot(1, bodyCount, 0)

def AddBodyCount(builder, bodyCount):
    FrameSampleAddBodyCount(builder, bodyCount)

def FrameSampleAddBodies(builder, bodies):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(bodies), 0)

def AddBodies(builder, bodies):
    FrameSampleAddBodies(builder, bodies)

def FrameSampleStartBodiesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartBodiesVector(builder, numElems):
    return FrameSampleStartBodiesVector(builder, numElems)

def FrameSampleCreateBodiesVector(builder, data):
    data = list(data)
    builder.StartVector(4, len(data), 4)
    for item in reversed(data):
        builder.PrependFloat32(item)
    return builder.EndVector()

def CreateBodiesVector(builder, data):
    FrameSampleCreateBodiesVector(builder, data)

def FrameSampleEnd(builder):
    return builder.EndObject()

def End(builder):
    return FrameSampleEnd(builder)
