#include "nBodySim.hpp"
#include <random>
#include <string>

void accretionDisk(ParticleSystem& system, size_t count);

void nBodyScenarios(ParticleSystem& system, size_t count);

void simpleGalaxy(ParticleSystem& system, size_t count);

void galaxyCollision(ParticleSystem& system, size_t count);

// Load initial conditions generated by AGAMA from a binary snapshot file.
// Returns true on success, false on parse/load errors.
bool loadAgamaSnapshot(ParticleSystem& system, const string& filePath);
