#include "nBodySim.hpp"
#include <random>
#include <string>

void accretionDisk(ParticleSystem& system, size_t count);

void threeBodies(ParticleSystem& system, size_t count);

void fourBodies(ParticleSystem& system, size_t count);

void fiveBodies(ParticleSystem& system, size_t count);

void sevenBodies(ParticleSystem& system, size_t count);

void tenBodies(ParticleSystem& system, size_t count);

void galaxyMilkyway(ParticleSystem& system, size_t count);

void milkyAndroCollision(ParticleSystem& system, size_t count);

// Load initial conditions generated by AGAMA from a binary snapshot file.
// Returns true on success, false on parse/load errors.
bool loadAgamaSnapshot(ParticleSystem& system, const string& filePath);
